# Generated by Django 3.0.5 on 2022-01-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Anonymous', max_length=30)),
                ('message', models.TextField(help_text='Birthday Message', null=True)),
            ],
        ),
    ]
